name: hammerhead-app
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: jhillbht/launch-analytics-1.2
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        type: SECRET
        value: ${GITHUB_TOKEN}
    routes:
      - path: /
    health_check:
      http_path: /health
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1